### PR TITLE
added tile3d to transitions

### PR DESCRIPTION
**Pull request by altryne**
Hey @Joe,
Found some time to add tile3d to flux. Took me some time hehe because of a small misplaced bug, but fixed it.
Didn't minify the flux.js tho...the tran is only in flux.js not in flux.min.js
Tell me what you think, if it's buggy etc.

### CODE REVIEW

**Comment by joelambert** [comment]
Great work, looks really awesome!

Unfortunately it doesn't work using Zepto though - I suspect this is because Zepto doesn't (and doesn't plan to) implement the full jQuery API.

Also, I don't think you need the recursion or the `setTimeout()` calls - take a look at this, I've modified it to make use of -`webkit-transition-delay` and put the tiles into containers so you're actually transitioning fewer DOM elements throughout the effect:

https://gist.github.com/982648 (incidentally also doesn't work with Zepto - no errors just doesn't work :-s !!)

My assumption is that by using transition delay rather than setTimeout we're passing more off to the GPU so timing will be tighter on iOS? What do you think?

**Comment by joelambert** [comment]
The above gist code now works with Zepto.js using the updated beta code in GitHub, incidentally also managed to adapt my modification of your code to another new transition:

`blinds3d` https://gist.github.com/982736

**Comment by altryne** [comment]
Lol yeah I was getting 3dblindes also when I didn't calculate the right cubes to rotate ;)

About the setTimeout vs transition delay, the thing is that setTimeout here doesn't do much. Only waits and then adds a css3 style to the element. It's not like in jqeury's animaiton where setTimeout goes everysecond and moves some div, this just adds css3 properties so the majority of the calculaiton is still on the GPU I think.

We could go crazy and add like 100 squares and test both mehtods I guess :)

**Comment by joelambert** [comment]
Presumably setting the CSS property is causing a reflow though? So does that mean that a reflow occurs each time a transition starts?

I suspect that using webkit-transition-duration allows the GPU to do the calculations and is more optimal?

Will test both approaches with large numbers of tiles

**Comment by joelambert** [comment]
Here's a video (annoyingly low quality - make sure you watch in 480p)

http://www.youtube.com/watch?v=GDgUb7NhLnY

I think the transition-delay (second in video) is a bit smoother, what do you think? Also with this number of dom elements I get a very short beach ball with your implementation, I assume this could be optimised by adding `currentFace` & `nextFace` to the dom after its contents have been populate?

**Comment by altryne** [comment]
Yup, seems a bit smoother, what do you mean a shorter beachball? :)

**Comment by joelambert** [comment]
I meant that the browser hung (gives a spinning beach ball on OS X). This is because the code is appending elements to the DOM on each loop & in turn causing a browser page reflow. If you populate the two container elements off-dom then push them at the end, the browser wont hang :)

**Comment by altryne** [comment]
Ooooooooh, on each setup() you mean, yeah I was wondering how to solve that, and I made portal before I saw the @paul_irish screencast on optimization.
Cool :)
btw something I wanted to solve and didn't manage in short time maybe ull have an Idea,
when I divided the height and length of the image to make the cubes, I Math.floor or Math.round the division
and sometimes the last tiles are a bit shorter then the edge of the container because of that.
Was thinking to solve it by checking if I'm calculating the width and height of the last tiles and row/column and doing something like width = total_width - tiles_beforeme.length \* tiles_before_me[0].width
Somehow it didn't quite work and it was late. :)
any ideas about that?

**Comment by joelambert** [comment]
Yeah I noticed that too - I'd solved that issue for bars3d so used the same technique for my mod of tiles3d. Check the gist, I work out how much extra to add and then space it out as regularly as possible. Means that the tiles/bars are always fill the available space exactly.

**Comment by altryne** [comment]
awesome! tiles3d are ported to flux!! _raises imaginery whiskey glass_
gonna hack on some more idea, let you know soon. (all 3d btw)
/closed

**Comment by altryne** [comment]
hey joe are you gonna merge this? I cloned the repo and there's no tiles3d anywhere there yet

**Comment by joelambert** [comment]
Sorry, was away at the weekend - you'll now find `tiles3d` in the js/src folder and I've re-built the code so its in `flux.js` & `flux.min.js`

**Comment by altryne** [comment]
Coolness, I'll add this to transitions demo from here.

**Pull request closed without merging**
